#!/bin/bash

sed -i '/<entry name="groupingStrategy" type="Enum">/,/<\/entry>/ s/<default>.*<\/default>/<default>0<\/default>/' /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml
sed -i '/<entry name="minimizeActiveTaskOnClick" type="Bool">/,/<\/entry>/ s/<default>.*<\/default>/<default>false<\/default>/' /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml
sed -i '/<entry name="wheelEnabled" type="Bool">/,/<\/entry>/ s/<default>.*<\/default>/<default>false<\/default>/' /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml
sed -i '/<entry name="launchers" type="StringList">/,/<\/entry>/ s/<default>.*<\/default>/<default>applications:systemsettings.desktop,preferred:\/\/filemanager<\/default>/' /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml

sed -i '/<entry name="favorites" type="StringList">/,/<\/entry>/ s/<default>.*<\/default>/<default><\/default>/' /usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/config/main.xml
sed -i '/<entry name="favoriteApps" type="StringList">/,/<\/entry>/ s/<default>.*<\/default>/<default><\/default>/' /usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/main.xml
