#!/bin/sh

makedeb() {
	mkdir -m 755 "$pkgdir/DEBIAN"
	install -D -m644 "$srcdir/control" "$pkgdir/DEBIAN/control"
	sed -i "s/^Package: .*\$/Package: $pkgname/" "$pkgdir/DEBIAN/control"
	sed -i "s/^Version: .*\$/Version: $pkgver/" "$pkgdir/DEBIAN/control"
	sed -i "s/^Description: .*\$/Description: $pkgdesc/" "$pkgdir/DEBIAN/control"

	mkdir -p $PKGDEST
	dpkg-deb --build "$pkgdir" "$PKGDEST/${pkgname}_${pkgver}-${pkgrel}_amd64.deb"

	exit $?
}
